name: Run Go Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  run_annotate_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'

      - name: run tests
        run: go test -json ./... > test.json

      - name: annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.3.0
        with:
          test-results: test.json